//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.19 at 03:36:55 PM CST 
//

package org.iii.ideas.catering_service.ws.schemav2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DeleteMenuRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DeleteMenuRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UploaderAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SchoolId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeleteMenuRequestType", propOrder = { "action", "messageId", "uploaderAccount", "token", "sendTime", "companyId", "serviceDate", "menuType", "schoolId" })
@XmlRootElement(name="DeleteMenuRequestType")
public class DeleteMenuRequestType {

	@XmlElement(name = "Action", required = true)
	protected String action;
	@XmlElement(name = "MessageId", required = true)
	protected String messageId;
	@XmlElement(name = "UploaderAccount", required = true)
	protected String uploaderAccount;
	@XmlElement(name = "Token", required = true)
	protected String token;
	@XmlElement(name = "SendTime")
	protected long sendTime;
	@XmlElement(name = "CompanyId", required = true)
	protected String companyId;
	@XmlElement(name = "ServiceDate", required = true)
	protected String serviceDate;
	@XmlElement(name = "MenuType", required = true)
	protected String menuType;
	@XmlElement(name = "SchoolId", required = true)
	protected String schoolId;

	/**
	 * Gets the value of the action property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAction() {
		return action;
	}

	/**
	 * Sets the value of the action property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAction(String value) {
		this.action = value;
	}

	/**
	 * Gets the value of the messageId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMessageId() {
		return messageId;
	}

	/**
	 * Sets the value of the messageId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMessageId(String value) {
		this.messageId = value;
	}

	/**
	 * Gets the value of the uploaderAccount property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUploaderAccount() {
		return uploaderAccount;
	}

	/**
	 * Sets the value of the uploaderAccount property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUploaderAccount(String value) {
		this.uploaderAccount = value;
	}

	/**
	 * Gets the value of the token property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getToken() {
		return token;
	}

	/**
	 * Sets the value of the token property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setToken(String value) {
		this.token = value;
	}

	/**
	 * Gets the value of the sendTime property.
	 * 
	 */
	public long getSendTime() {
		return sendTime;
	}

	/**
	 * Sets the value of the sendTime property.
	 * 
	 */
	public void setSendTime(long value) {
		this.sendTime = value;
	}

	/**
	 * Gets the value of the companyId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * Sets the value of the companyId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompanyId(String value) {
		this.companyId = value;
	}

	/**
	 * Gets the value of the serviceDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getServiceDate() {
		return serviceDate;
	}

	/**
	 * Sets the value of the serviceDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setServiceDate(String value) {
		this.serviceDate = value;
	}

	public String getMenuType() {
		return menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	/**
	 * Gets the value of the schoolId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSchoolId() {
		return schoolId;
	}

	/**
	 * Sets the value of the schoolId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSchoolId(String value) {
		this.schoolId = value;
	}

}
