//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.19 at 03:36:55 PM CST 
//


package org.iii.ideas.catering_service.ws.schemav2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DishesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DishesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dish" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DishType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DishInfo" type="{http://twfoodtrace.org.tw/FcloudDataschemas}DishInfo"/>
 *                   &lt;element name="DisplayOrder" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="DishQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DishesType", propOrder = {
    "dish"
})
public class DishesType {

    @XmlElement(name = "Dish", required = true)
    protected List<DishesType.Dish> dish;

    /**
     * Gets the value of the dish property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dish property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDish().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DishesType.Dish }
     * 
     * 
     */
    public List<DishesType.Dish> getDish() {
        if (dish == null) {
            dish = new ArrayList<DishesType.Dish>();
        }
        return this.dish;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DishType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DishInfo" type="{http://twfoodtrace.org.tw/FcloudDataschemas}DishInfo"/>
     *         &lt;element name="DisplayOrder" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="DishQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dishType",
        "dishInfo",
        "displayOrder",
        "dishQuantity"
    })
    public static class Dish {

        @XmlElement(name = "DishType", required = true)
        protected String dishType;
        @XmlElement(name = "DishInfo", required = true)
        protected DishInfo dishInfo;
        @XmlElement(name = "DisplayOrder", required = true)
        protected BigDecimal displayOrder;
        @XmlElement(name = "DishQuantity")
        protected BigDecimal dishQuantity;

        /**
         * Gets the value of the dishType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDishType() {
            return dishType;
        }

        /**
         * Sets the value of the dishType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDishType(String value) {
            this.dishType = value;
        }

        /**
         * Gets the value of the dishInfo property.
         * 
         * @return
         *     possible object is
         *     {@link DishInfo }
         *     
         */
        public DishInfo getDishInfo() {
            return dishInfo;
        }

        /**
         * Sets the value of the dishInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link DishInfo }
         *     
         */
        public void setDishInfo(DishInfo value) {
            this.dishInfo = value;
        }

        /**
         * Gets the value of the displayOrder property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDisplayOrder() {
            return displayOrder;
        }

        /**
         * Sets the value of the displayOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDisplayOrder(BigDecimal value) {
            this.displayOrder = value;
        }

        /**
         * Gets the value of the dishQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDishQuantity() {
            return dishQuantity;
        }

        /**
         * Sets the value of the dishQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDishQuantity(BigDecimal value) {
            this.dishQuantity = value;
        }

    }

}
