//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.19 at 03:36:55 PM CST 
//


package org.iii.ideas.catering_service.ws.schemav2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneticallyModifiedFoodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneticallyModifiedFoodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeneticallyModifiedFood" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FoodCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneticallyModifiedFoodType", propOrder = {
    "geneticallyModifiedFood"
})
public class GeneticallyModifiedFoodType {

    @XmlElement(name = "GeneticallyModifiedFood", required = true)
    protected List<GeneticallyModifiedFoodType.GeneticallyModifiedFood> geneticallyModifiedFood;

    /**
     * Gets the value of the geneticallyModifiedFood property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geneticallyModifiedFood property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneticallyModifiedFood().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneticallyModifiedFoodType.GeneticallyModifiedFood }
     * 
     * 
     */
    public List<GeneticallyModifiedFoodType.GeneticallyModifiedFood> getGeneticallyModifiedFood() {
        if (geneticallyModifiedFood == null) {
            geneticallyModifiedFood = new ArrayList<GeneticallyModifiedFoodType.GeneticallyModifiedFood>();
        }
        return this.geneticallyModifiedFood;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FoodCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "foodCode"
    })
    public static class GeneticallyModifiedFood {

        @XmlElement(name = "FoodCode", required = true)
        protected String foodCode;

        /**
         * Gets the value of the foodCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFoodCode() {
            return foodCode;
        }

        /**
         * Sets the value of the foodCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFoodCode(String value) {
            this.foodCode = value;
        }

    }

}
