//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 10:52:20 AM CST 
//


package org.iii.ideas.catering_service.ws.schemav2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iii.ideas.catering_service.ws.schemav2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UploadIngredientResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadIngredientResponse");
    private final static QName _UploadCompanyRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadCompanyRequest");
    private final static QName _UploadIngredientRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadIngredientRequest");
    private final static QName _UploadCustomerInfoResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadCustomerInfoResponse");
    private final static QName _UploadSupplierRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadSupplierRequest");
    private final static QName _UploadCustomerInfoRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadCustomerInfoRequest");
    private final static QName _DeleteSupplierRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "DeleteSupplierRequest");
    private final static QName _DeleteMenuResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "DeleteMenuResponse");
    private final static QName _DeleteMenuRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "DeleteMenuRequest");
    private final static QName _UploadMenuResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadMenuResponse");
    private final static QName _UploadProductResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadProductResponse");
    private final static QName _UploadProductRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadProductRequest");
    private final static QName _UploadMenuRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadMenuRequest");
    private final static QName _UploadSchoolProductRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadSchoolProductRequest");
    private final static QName _UploadNoMenuDateRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadNoMenuDateRequest");
    private final static QName _UploadCompanyResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadCompanyResponse");
    private final static QName _DeleteSupplierResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "DeleteSupplierResponse");
    private final static QName _UploadNoMenuDateResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadNoMenuDateResponse");
    private final static QName _UploadSchoolProductResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadSchoolProductResponse");
    private final static QName _UploadSupplierResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadSupplierResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iii.ideas.catering_service.ws.schemav2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeneticallyModifiedFoodType }
     * 
     */
    public GeneticallyModifiedFoodType createGeneticallyModifiedFoodType() {
        return new GeneticallyModifiedFoodType();
    }

    /**
     * Create an instance of {@link DishesType }
     * 
     */
    public DishesType createDishesType() {
        return new DishesType();
    }

    /**
     * Create an instance of {@link UploadIngredientRequestType }
     * 
     */
    public UploadIngredientRequestType createUploadIngredientRequestType() {
        return new UploadIngredientRequestType();
    }

    /**
     * Create an instance of {@link UploadIngredientRequestType.Sources }
     * 
     */
    public UploadIngredientRequestType.Sources createUploadIngredientRequestTypeSources() {
        return new UploadIngredientRequestType.Sources();
    }

    /**
     * Create an instance of {@link UploadIngredientRequestType.Sources.SourceItem }
     * 
     */
    public UploadIngredientRequestType.Sources.SourceItem createUploadIngredientRequestTypeSourcesSourceItem() {
        return new UploadIngredientRequestType.Sources.SourceItem();
    }

    /**
     * Create an instance of {@link FoodResponseTypev2 }
     * 
     */
    public FoodResponseTypev2 createFoodResponseTypev2() {
        return new FoodResponseTypev2();
    }

    /**
     * Create an instance of {@link UploadNoMenuDateRequestType }
     * 
     */
    public UploadNoMenuDateRequestType createUploadNoMenuDateRequestType() {
        return new UploadNoMenuDateRequestType();
    }

    /**
     * Create an instance of {@link UploadProductRequestType }
     * 
     */
    public UploadProductRequestType createUploadProductRequestType() {
        return new UploadProductRequestType();
    }

    /**
     * Create an instance of {@link UploadMenuRequestType }
     * 
     */
    public UploadMenuRequestType createUploadMenuRequestType() {
        return new UploadMenuRequestType();
    }

    /**
     * Create an instance of {@link UploadSchoolProductRequestType }
     * 
     */
    public UploadSchoolProductRequestType createUploadSchoolProductRequestType() {
        return new UploadSchoolProductRequestType();
    }

    /**
     * Create an instance of {@link UploadSupplierRequestType }
     * 
     */
    public UploadSupplierRequestType createUploadSupplierRequestType() {
        return new UploadSupplierRequestType();
    }

    /**
     * Create an instance of {@link UploadCompanyRequestType }
     * 
     */
    public UploadCompanyRequestType createUploadCompanyRequestType() {
        return new UploadCompanyRequestType();
    }

    /**
     * Create an instance of {@link DeleteMenuRequestType }
     * 
     */
    public DeleteMenuRequestType createDeleteMenuRequestType() {
        return new DeleteMenuRequestType();
    }

    /**
     * Create an instance of {@link UploadCustomerInfoRequestType }
     * 
     */
    public UploadCustomerInfoRequestType createUploadCustomerInfoRequestType() {
        return new UploadCustomerInfoRequestType();
    }

    /**
     * Create an instance of {@link DeleteSupplierRequestType }
     * 
     */
    public DeleteSupplierRequestType createDeleteSupplierRequestType() {
        return new DeleteSupplierRequestType();
    }

    /**
     * Create an instance of {@link DishInfo }
     * 
     */
    public DishInfo createDishInfo() {
        return new DishInfo();
    }

    /**
     * Create an instance of {@link GeneticallyModifiedFoodType.GeneticallyModifiedFood }
     * 
     */
    public GeneticallyModifiedFoodType.GeneticallyModifiedFood createGeneticallyModifiedFoodTypeGeneticallyModifiedFood() {
        return new GeneticallyModifiedFoodType.GeneticallyModifiedFood();
    }

    /**
     * Create an instance of {@link DishesType.Dish }
     * 
     */
    public DishesType.Dish createDishesTypeDish() {
        return new DishesType.Dish();
    }

    /**
     * Create an instance of {@link UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile }
     * 
     */
    public UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile createUploadIngredientRequestTypeSourcesSourceItemSourceInspectionFile() {
        return new UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadIngredientResponse")
    public JAXBElement<FoodResponseTypev2> createUploadIngredientResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadIngredientResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadCompanyRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadCompanyRequest")
    public JAXBElement<UploadCompanyRequestType> createUploadCompanyRequest(UploadCompanyRequestType value) {
        return new JAXBElement<UploadCompanyRequestType>(_UploadCompanyRequest_QNAME, UploadCompanyRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadIngredientRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadIngredientRequest")
    public JAXBElement<UploadIngredientRequestType> createUploadIngredientRequest(UploadIngredientRequestType value) {
        return new JAXBElement<UploadIngredientRequestType>(_UploadIngredientRequest_QNAME, UploadIngredientRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadCustomerInfoResponse")
    public JAXBElement<FoodResponseTypev2> createUploadCustomerInfoResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadCustomerInfoResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadSupplierRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadSupplierRequest")
    public JAXBElement<UploadSupplierRequestType> createUploadSupplierRequest(UploadSupplierRequestType value) {
        return new JAXBElement<UploadSupplierRequestType>(_UploadSupplierRequest_QNAME, UploadSupplierRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadCustomerInfoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadCustomerInfoRequest")
    public JAXBElement<UploadCustomerInfoRequestType> createUploadCustomerInfoRequest(UploadCustomerInfoRequestType value) {
        return new JAXBElement<UploadCustomerInfoRequestType>(_UploadCustomerInfoRequest_QNAME, UploadCustomerInfoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteSupplierRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "DeleteSupplierRequest")
    public JAXBElement<DeleteSupplierRequestType> createDeleteSupplierRequest(DeleteSupplierRequestType value) {
        return new JAXBElement<DeleteSupplierRequestType>(_DeleteSupplierRequest_QNAME, DeleteSupplierRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "DeleteMenuResponse")
    public JAXBElement<FoodResponseTypev2> createDeleteMenuResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_DeleteMenuResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMenuRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "DeleteMenuRequest")
    public JAXBElement<DeleteMenuRequestType> createDeleteMenuRequest(DeleteMenuRequestType value) {
        return new JAXBElement<DeleteMenuRequestType>(_DeleteMenuRequest_QNAME, DeleteMenuRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadMenuResponse")
    public JAXBElement<FoodResponseTypev2> createUploadMenuResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadMenuResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadProductResponse")
    public JAXBElement<FoodResponseTypev2> createUploadProductResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadProductResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadProductRequest")
    public JAXBElement<UploadProductRequestType> createUploadProductRequest(UploadProductRequestType value) {
        return new JAXBElement<UploadProductRequestType>(_UploadProductRequest_QNAME, UploadProductRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadMenuRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadMenuRequest")
    public JAXBElement<UploadMenuRequestType> createUploadMenuRequest(UploadMenuRequestType value) {
        return new JAXBElement<UploadMenuRequestType>(_UploadMenuRequest_QNAME, UploadMenuRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadSchoolProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadSchoolProductRequest")
    public JAXBElement<UploadSchoolProductRequestType> createUploadSchoolProductRequest(UploadSchoolProductRequestType value) {
        return new JAXBElement<UploadSchoolProductRequestType>(_UploadSchoolProductRequest_QNAME, UploadSchoolProductRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadNoMenuDateRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadNoMenuDateRequest")
    public JAXBElement<UploadNoMenuDateRequestType> createUploadNoMenuDateRequest(UploadNoMenuDateRequestType value) {
        return new JAXBElement<UploadNoMenuDateRequestType>(_UploadNoMenuDateRequest_QNAME, UploadNoMenuDateRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadCompanyResponse")
    public JAXBElement<FoodResponseTypev2> createUploadCompanyResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadCompanyResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "DeleteSupplierResponse")
    public JAXBElement<FoodResponseTypev2> createDeleteSupplierResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_DeleteSupplierResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadNoMenuDateResponse")
    public JAXBElement<FoodResponseTypev2> createUploadNoMenuDateResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadNoMenuDateResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadSchoolProductResponse")
    public JAXBElement<FoodResponseTypev2> createUploadSchoolProductResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadSchoolProductResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseTypev2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadSupplierResponse")
    public JAXBElement<FoodResponseTypev2> createUploadSupplierResponse(FoodResponseTypev2 value) {
        return new JAXBElement<FoodResponseTypev2>(_UploadSupplierResponse_QNAME, FoodResponseTypev2 .class, null, value);
    }

}
