//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.19 at 03:36:55 PM CST 
//


package org.iii.ideas.catering_service.ws.schemav2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UploadIngredientRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UploadIngredientRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UploaderAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SchoolId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SourceItem" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DishesName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Brands" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ManufacturerBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="BrandsBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SupplierId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SourceCertification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="CertificationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="StockDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ManufactureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="LotNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SourceInspectionFile">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SourceInspectionFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="GeneticallyModifiedFoodList" type="{http://twfoodtrace.org.tw/FcloudDataschemas}GeneticallyModifiedFoodType" minOccurs="0"/>
 *                             &lt;element name="IngredientQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="IngredientUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ProcessedFood" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UploadIngredientRequestType", propOrder = {
    "action",
    "messageId",
    "uploaderAccount",
    "token",
    "sendTime",
    "companyId",
    "serviceDate",
    "menuType",
    "schoolId",
    "sources"
})
@XmlRootElement(name="UploadIngredientRequestType")
public class UploadIngredientRequestType {

    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "MessageId", required = true)
    protected String messageId;
    @XmlElement(name = "UploaderAccount", required = true)
    protected String uploaderAccount;
    @XmlElement(name = "Token", required = true)
    protected String token;
    @XmlElement(name = "SendTime")
    protected long sendTime;
    @XmlElement(name = "CompanyId", required = true)
    protected String companyId;
    @XmlElement(name = "ServiceDate", required = true)
    protected String serviceDate;
    @XmlElement(name = "MenuType", required = true)
    protected String menuType;
    @XmlElement(name = "SchoolId", required = true)
    protected String schoolId;
    @XmlElement(name = "Sources", required = true)
    protected UploadIngredientRequestType.Sources sources;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the uploaderAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploaderAccount() {
        return uploaderAccount;
    }

    /**
     * Sets the value of the uploaderAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploaderAccount(String value) {
        this.uploaderAccount = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the sendTime property.
     * 
     */
    public long getSendTime() {
        return sendTime;
    }

    /**
     * Sets the value of the sendTime property.
     * 
     */
    public void setSendTime(long value) {
        this.sendTime = value;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyId(String value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the serviceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDate() {
        return serviceDate;
    }

    /**
     * Sets the value of the serviceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDate(String value) {
        this.serviceDate = value;
    }

    public String getMenuType() {
		return menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	/**
     * Gets the value of the schoolId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * Sets the value of the schoolId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolId(String value) {
        this.schoolId = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link UploadIngredientRequestType.Sources }
     *     
     */
    public UploadIngredientRequestType.Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadIngredientRequestType.Sources }
     *     
     */
    public void setSources(UploadIngredientRequestType.Sources value) {
        this.sources = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SourceItem" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DishesName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Brands" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ManufacturerBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="BrandsBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SupplierId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SourceCertification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="CertificationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="StockDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ManufactureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="LotNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SourceInspectionFile">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SourceInspectionFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="GeneticallyModifiedFoodList" type="{http://twfoodtrace.org.tw/FcloudDataschemas}GeneticallyModifiedFoodType" minOccurs="0"/>
     *                   &lt;element name="IngredientQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="IngredientUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ProcessedFood" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sourceItem"
    })
    public static class Sources {

        @XmlElement(name = "SourceItem", required = true)
        protected List<UploadIngredientRequestType.Sources.SourceItem> sourceItem;

        /**
         * Gets the value of the sourceItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sourceItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSourceItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UploadIngredientRequestType.Sources.SourceItem }
         * 
         * 
         */
        public List<UploadIngredientRequestType.Sources.SourceItem> getSourceItem() {
            if (sourceItem == null) {
                sourceItem = new ArrayList<UploadIngredientRequestType.Sources.SourceItem>();
            }
            return this.sourceItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DishesName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Brands" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ManufacturerBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="BrandsBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SupplierId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SourceCertification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="CertificationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="StockDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ManufactureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="LotNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SourceInspectionFile">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SourceInspectionFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="GeneticallyModifiedFoodList" type="{http://twfoodtrace.org.tw/FcloudDataschemas}GeneticallyModifiedFoodType" minOccurs="0"/>
         *         &lt;element name="IngredientQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="IngredientUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ProcessedFood" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dishesName",
            "sourceName",
            "brands",
            "productName",
            "manufacturer",
            "manufacturerBAN",
            "brandsBAN",
            "origin",
            "source",
            "supplierId",
            "supplierName",
            "sourceCertification",
            "certificationID",
            "stockDate",
            "manufactureDate",
            "expirationDate",
            "lotNumber",
            "sourceInspectionFile",
            "geneticallyModifiedFoodList",
            "ingredientQuantity",
            "ingredientUnit",
            "processedFood"
        })
        public static class SourceItem {

            @XmlElement(name = "DishesName", required = true)
            protected String dishesName;
            @XmlElement(name = "SourceName", required = true)
            protected String sourceName;
            @XmlElement(name = "Brands")
            protected String brands;
            @XmlElement(name = "ProductName")
            protected String productName;
            @XmlElement(name = "Manufacturer")
            protected String manufacturer;
            @XmlElement(name = "ManufacturerBAN")
            protected String manufacturerBAN;
            @XmlElement(name = "BrandsBAN")
            protected String brandsBAN;
            @XmlElement(name = "Origin")
            protected String origin;
            @XmlElement(name = "Source", required = true)
            protected String source;
            @XmlElement(name = "SupplierId", required = true)
            protected String supplierId;
            @XmlElement(name = "SupplierName", required = true)
            protected String supplierName;
            @XmlElement(name = "SourceCertification")
            protected String sourceCertification;
            @XmlElement(name = "CertificationID")
            protected String certificationID;
            @XmlElement(name = "StockDate", required = true)
            protected String stockDate;
            @XmlElement(name = "ManufactureDate")
            protected String manufactureDate;
            @XmlElement(name = "ExpirationDate")
            protected String expirationDate;
            @XmlElement(name = "LotNumber")
            protected String lotNumber;
            @XmlElement(name = "SourceInspectionFile", required = true)
            protected UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile sourceInspectionFile;
            @XmlElement(name = "GeneticallyModifiedFoodList")
            protected GeneticallyModifiedFoodType geneticallyModifiedFoodList;
            @XmlElement(name = "IngredientQuantity")
            protected BigDecimal ingredientQuantity;
            @XmlElement(name = "IngredientUnit")
            protected String ingredientUnit;
            @XmlElement(name = "ProcessedFood")
            protected String processedFood;

            /**
             * Gets the value of the dishesName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDishesName() {
                return dishesName;
            }

            /**
             * Sets the value of the dishesName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDishesName(String value) {
                this.dishesName = value;
            }

            /**
             * Gets the value of the sourceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceName() {
                return sourceName;
            }

            /**
             * Sets the value of the sourceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceName(String value) {
                this.sourceName = value;
            }

            /**
             * Gets the value of the brands property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrands() {
                return brands;
            }

            /**
             * Sets the value of the brands property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrands(String value) {
                this.brands = value;
            }

            /**
             * Gets the value of the productName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductName() {
                return productName;
            }

            /**
             * Sets the value of the productName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductName(String value) {
                this.productName = value;
            }

            /**
             * Gets the value of the manufacturer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getManufacturer() {
                return manufacturer;
            }

            /**
             * Sets the value of the manufacturer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setManufacturer(String value) {
                this.manufacturer = value;
            }

            /**
             * Gets the value of the manufacturerBAN property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getManufacturerBAN() {
                return manufacturerBAN;
            }

            /**
             * Sets the value of the manufacturerBAN property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setManufacturerBAN(String value) {
                this.manufacturerBAN = value;
            }

            /**
             * Gets the value of the brandsBAN property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrandsBAN() {
                return brandsBAN;
            }

            /**
             * Sets the value of the brandsBAN property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrandsBAN(String value) {
                this.brandsBAN = value;
            }

            /**
             * Gets the value of the origin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrigin() {
                return origin;
            }

            /**
             * Sets the value of the origin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrigin(String value) {
                this.origin = value;
            }

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the supplierId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupplierId() {
                return supplierId;
            }

            /**
             * Sets the value of the supplierId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupplierId(String value) {
                this.supplierId = value;
            }

            /**
             * Gets the value of the supplierName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupplierName() {
                return supplierName;
            }

            /**
             * Sets the value of the supplierName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupplierName(String value) {
                this.supplierName = value;
            }

            /**
             * Gets the value of the sourceCertification property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceCertification() {
                return sourceCertification;
            }

            /**
             * Sets the value of the sourceCertification property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceCertification(String value) {
                this.sourceCertification = value;
            }

            /**
             * Gets the value of the certificationID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCertificationID() {
                return certificationID;
            }

            /**
             * Sets the value of the certificationID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCertificationID(String value) {
                this.certificationID = value;
            }

            /**
             * Gets the value of the stockDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStockDate() {
                return stockDate;
            }

            /**
             * Sets the value of the stockDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStockDate(String value) {
                this.stockDate = value;
            }

            /**
             * Gets the value of the manufactureDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getManufactureDate() {
                return manufactureDate;
            }

            /**
             * Sets the value of the manufactureDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setManufactureDate(String value) {
                this.manufactureDate = value;
            }

            /**
             * Gets the value of the expirationDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpirationDate() {
                return expirationDate;
            }

            /**
             * Sets the value of the expirationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpirationDate(String value) {
                this.expirationDate = value;
            }

            /**
             * Gets the value of the lotNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLotNumber() {
                return lotNumber;
            }

            /**
             * Sets the value of the lotNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLotNumber(String value) {
                this.lotNumber = value;
            }

            /**
             * Gets the value of the sourceInspectionFile property.
             * 
             * @return
             *     possible object is
             *     {@link UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile }
             *     
             */
            public UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile getSourceInspectionFile() {
                return sourceInspectionFile;
            }

            /**
             * Sets the value of the sourceInspectionFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile }
             *     
             */
            public void setSourceInspectionFile(UploadIngredientRequestType.Sources.SourceItem.SourceInspectionFile value) {
                this.sourceInspectionFile = value;
            }

            /**
             * Gets the value of the geneticallyModifiedFoodList property.
             * 
             * @return
             *     possible object is
             *     {@link GeneticallyModifiedFoodType }
             *     
             */
            public GeneticallyModifiedFoodType getGeneticallyModifiedFoodList() {
                return geneticallyModifiedFoodList;
            }

            /**
             * Sets the value of the geneticallyModifiedFoodList property.
             * 
             * @param value
             *     allowed object is
             *     {@link GeneticallyModifiedFoodType }
             *     
             */
            public void setGeneticallyModifiedFoodList(GeneticallyModifiedFoodType value) {
                this.geneticallyModifiedFoodList = value;
            }

            /**
             * Gets the value of the ingredientQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getIngredientQuantity() {
                return ingredientQuantity;
            }

            /**
             * Sets the value of the ingredientQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setIngredientQuantity(BigDecimal value) {
                this.ingredientQuantity = value;
            }

            /**
             * Gets the value of the ingredientUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIngredientUnit() {
                return ingredientUnit;
            }

            /**
             * Sets the value of the ingredientUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIngredientUnit(String value) {
                this.ingredientUnit = value;
            }

            /**
             * Gets the value of the processedFood property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProcessedFood() {
                return processedFood;
            }

            /**
             * Sets the value of the processedFood property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProcessedFood(String value) {
                this.processedFood = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SourceInspectionFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "sourceInspectionFileName",
                "sourceIngredientsInspectionLab",
                "sourceIngredientsInspectionStatus"
            })
            public static class SourceInspectionFile {

                @XmlElement(name = "SourceInspectionFileName")
                protected String sourceInspectionFileName;
                @XmlElement(name = "SourceIngredientsInspectionLab")
                protected String sourceIngredientsInspectionLab;
                @XmlElement(name = "SourceIngredientsInspectionStatus")
                protected String sourceIngredientsInspectionStatus;

                /**
                 * Gets the value of the sourceInspectionFileName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceInspectionFileName() {
                    return sourceInspectionFileName;
                }

                /**
                 * Sets the value of the sourceInspectionFileName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceInspectionFileName(String value) {
                    this.sourceInspectionFileName = value;
                }

                /**
                 * Gets the value of the sourceIngredientsInspectionLab property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceIngredientsInspectionLab() {
                    return sourceIngredientsInspectionLab;
                }

                /**
                 * Sets the value of the sourceIngredientsInspectionLab property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceIngredientsInspectionLab(String value) {
                    this.sourceIngredientsInspectionLab = value;
                }

                /**
                 * Gets the value of the sourceIngredientsInspectionStatus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceIngredientsInspectionStatus() {
                    return sourceIngredientsInspectionStatus;
                }

                /**
                 * Sets the value of the sourceIngredientsInspectionStatus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceIngredientsInspectionStatus(String value) {
                    this.sourceIngredientsInspectionStatus = value;
                }

            }

        }

    }

}
