//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.13 at 04:51:15 PM CST 
//


package org.iii.ideas.catering_service.ws.schemav2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UploadBatchProductRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UploadBatchProductRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SchoolId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UploaderAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SourceItem" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DishesName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Brands" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SupplierId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SourceCertification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="CertificationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="StockDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ManufactureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="LotNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SourceInspectionFileList">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SourceInspectionFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UploadBatchProductRequestType", propOrder = {
    "action",
    "messageId",
    "companyId",
    "schoolId",
    "serviceDate",
    "uploaderAccount",
    "sources"
})
@XmlRootElement(name="UploadBatchProductRequestType")
public class UploadBatchProductRequestType {

    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "MessageId", required = true)
    protected String messageId;
    @XmlElement(name = "CompanyId", required = true)
    protected String companyId;
    @XmlElement(name = "SchoolId", required = true)
    protected String schoolId;
    @XmlElement(name = "ServiceDate", required = true)
    protected String serviceDate;
    @XmlElement(name = "UploaderAccount", required = true)
    protected String uploaderAccount;
    @XmlElement(name = "Sources", required = true)
    protected UploadBatchProductRequestType.Sources sources;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyId(String value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the schoolId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * Sets the value of the schoolId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolId(String value) {
        this.schoolId = value;
    }

    /**
     * Gets the value of the serviceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDate() {
        return serviceDate;
    }

    /**
     * Sets the value of the serviceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDate(String value) {
        this.serviceDate = value;
    }

    /**
     * Gets the value of the uploaderAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploaderAccount() {
        return uploaderAccount;
    }

    /**
     * Sets the value of the uploaderAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploaderAccount(String value) {
        this.uploaderAccount = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link UploadBatchProductRequestType.Sources }
     *     
     */
    public UploadBatchProductRequestType.Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadBatchProductRequestType.Sources }
     *     
     */
    public void setSources(UploadBatchProductRequestType.Sources value) {
        this.sources = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SourceItem" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DishesName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Brands" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SupplierId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SourceCertification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="CertificationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="StockDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ManufactureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="LotNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SourceInspectionFileList">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SourceInspectionFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sourceItem"
    })
    public static class Sources {

        @XmlElement(name = "SourceItem", required = true)
        protected List<UploadBatchProductRequestType.Sources.SourceItem> sourceItem;

        /**
         * Gets the value of the sourceItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sourceItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSourceItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UploadBatchProductRequestType.Sources.SourceItem }
         * 
         * 
         */
        public List<UploadBatchProductRequestType.Sources.SourceItem> getSourceItem() {
            if (sourceItem == null) {
                sourceItem = new ArrayList<UploadBatchProductRequestType.Sources.SourceItem>();
            }
            return this.sourceItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DishesName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Brands" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SupplierId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SourceCertification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="CertificationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="StockDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ManufactureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="LotNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SourceInspectionFileList">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SourceInspectionFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dishesName",
            "sourceName",
            "brands",
            "origin",
            "source",
            "supplierId",
            "supplierName",
            "sourceCertification",
            "certificationID",
            "stockDate",
            "manufactureDate",
            "expirationDate",
            "lotNumber",
            "sourceInspectionFileList"
        })
        public static class SourceItem {

            @XmlElement(name = "DishesName", required = true)
            protected String dishesName;
            @XmlElement(name = "SourceName", required = true)
            protected String sourceName;
            @XmlElement(name = "Brands")
            protected String brands;
            @XmlElement(name = "Origin")
            protected String origin;
            @XmlElement(name = "Source", required = true)
            protected String source;
            @XmlElement(name = "SupplierId", required = true)
            protected String supplierId;
            @XmlElement(name = "SupplierName", required = true)
            protected String supplierName;
            @XmlElement(name = "SourceCertification")
            protected String sourceCertification;
            @XmlElement(name = "CertificationID")
            protected String certificationID;
            @XmlElement(name = "StockDate", required = true)
            protected String stockDate;
            @XmlElement(name = "ManufactureDate")
            protected String manufactureDate;
            @XmlElement(name = "ExpirationDate")
            protected String expirationDate;
            @XmlElement(name = "LotNumber")
            protected String lotNumber;
            @XmlElement(name = "SourceInspectionFileList", required = true)
            protected UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList sourceInspectionFileList;

            /**
             * Gets the value of the dishesName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDishesName() {
                return dishesName;
            }

            /**
             * Sets the value of the dishesName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDishesName(String value) {
                this.dishesName = value;
            }

            /**
             * Gets the value of the sourceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceName() {
                return sourceName;
            }

            /**
             * Sets the value of the sourceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceName(String value) {
                this.sourceName = value;
            }

            /**
             * Gets the value of the brands property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrands() {
                return brands;
            }

            /**
             * Sets the value of the brands property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrands(String value) {
                this.brands = value;
            }

            /**
             * Gets the value of the origin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrigin() {
                return origin;
            }

            /**
             * Sets the value of the origin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrigin(String value) {
                this.origin = value;
            }

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the supplierId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupplierId() {
                return supplierId;
            }

            /**
             * Sets the value of the supplierId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupplierId(String value) {
                this.supplierId = value;
            }

            /**
             * Gets the value of the supplierName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupplierName() {
                return supplierName;
            }

            /**
             * Sets the value of the supplierName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupplierName(String value) {
                this.supplierName = value;
            }

            /**
             * Gets the value of the sourceCertification property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceCertification() {
                return sourceCertification;
            }

            /**
             * Sets the value of the sourceCertification property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceCertification(String value) {
                this.sourceCertification = value;
            }

            /**
             * Gets the value of the certificationID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCertificationID() {
                return certificationID;
            }

            /**
             * Sets the value of the certificationID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCertificationID(String value) {
                this.certificationID = value;
            }

            /**
             * Gets the value of the stockDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStockDate() {
                return stockDate;
            }

            /**
             * Sets the value of the stockDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStockDate(String value) {
                this.stockDate = value;
            }

            /**
             * Gets the value of the manufactureDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getManufactureDate() {
                return manufactureDate;
            }

            /**
             * Sets the value of the manufactureDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setManufactureDate(String value) {
                this.manufactureDate = value;
            }

            /**
             * Gets the value of the expirationDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpirationDate() {
                return expirationDate;
            }

            /**
             * Sets the value of the expirationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpirationDate(String value) {
                this.expirationDate = value;
            }

            /**
             * Gets the value of the lotNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLotNumber() {
                return lotNumber;
            }

            /**
             * Sets the value of the lotNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLotNumber(String value) {
                this.lotNumber = value;
            }

            /**
             * Gets the value of the sourceInspectionFileList property.
             * 
             * @return
             *     possible object is
             *     {@link UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList }
             *     
             */
            public UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList getSourceInspectionFileList() {
                return sourceInspectionFileList;
            }

            /**
             * Sets the value of the sourceInspectionFileList property.
             * 
             * @param value
             *     allowed object is
             *     {@link UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList }
             *     
             */
            public void setSourceInspectionFileList(UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList value) {
                this.sourceInspectionFileList = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SourceInspectionFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="SourceIngredientsInspectionLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="SourceIngredientsInspectionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "sourceInspectionFile",
                "sourceIngredientsInspectionLab",
                "sourceIngredientsInspectionStatus"
            })
            public static class SourceInspectionFileList {

                @XmlElement(name = "SourceInspectionFile")
                protected String sourceInspectionFile;
                @XmlElement(name = "SourceIngredientsInspectionLab")
                protected String sourceIngredientsInspectionLab;
                @XmlElement(name = "SourceIngredientsInspectionStatus")
                protected String sourceIngredientsInspectionStatus;

                /**
                 * Gets the value of the sourceInspectionFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceInspectionFile() {
                    return sourceInspectionFile;
                }

                /**
                 * Sets the value of the sourceInspectionFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceInspectionFile(String value) {
                    this.sourceInspectionFile = value;
                }

                /**
                 * Gets the value of the sourceIngredientsInspectionLab property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceIngredientsInspectionLab() {
                    return sourceIngredientsInspectionLab;
                }

                /**
                 * Sets the value of the sourceIngredientsInspectionLab property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceIngredientsInspectionLab(String value) {
                    this.sourceIngredientsInspectionLab = value;
                }

                /**
                 * Gets the value of the sourceIngredientsInspectionStatus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceIngredientsInspectionStatus() {
                    return sourceIngredientsInspectionStatus;
                }

                /**
                 * Sets the value of the sourceIngredientsInspectionStatus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceIngredientsInspectionStatus(String value) {
                    this.sourceIngredientsInspectionStatus = value;
                }

            }

        }

    }

}
