package org.iii.ideas.catering_service.dao;

//Generated 2015/2/3 上午 09:25:59 by Hibernate Tools 3.4.0.CR1

/**
* SfCountyproductcategory generated by hbm2java
*/
public abstract class AbstractSfCountyProductSet implements java.io.Serializable {

	private Long id;
	private int countyId;
	private long productId;
	private String onShelfDate;
	private String offShelfDate;

	public AbstractSfCountyProductSet() {
	}

	public AbstractSfCountyProductSet(int countyId, long productId, String onShelfDate) {
		this.countyId = countyId;
		this.productId = productId;
		this.onShelfDate = onShelfDate;
	}

	public AbstractSfCountyProductSet(int countyId, long productId, String onShelfDate,
			String offShelfDate) {
		this.countyId = countyId;
		this.productId = productId;
		this.onShelfDate = onShelfDate;
		this.offShelfDate = offShelfDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getCountyId() {
		return this.countyId;
	}

	public void setCountyId(int countyId) {
		this.countyId = countyId;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getOnShelfDate() {
		return this.onShelfDate;
	}

	public void setOnShelfDate(String onShelfDate) {
		this.onShelfDate = onShelfDate;
	}

	public String getOffShelfDate() {
		return this.offShelfDate;
	}

	public void setOffShelfDate(String offShelfDate) {
		this.offShelfDate = offShelfDate;
	}
}