package org.iii.ideas.catering_service.dao;

//Generated 2015/2/3 上午 09:25:59 by Hibernate Tools 3.4.0.CR1

/**
* SfPrevSoldCode generated by hbm2java
*/
public abstract class AbstractSfPrevSoldCode implements java.io.Serializable {

	private int codeId;
	private int codeType;
	private String code;
	private String codeName;

	public AbstractSfPrevSoldCode() {
	}

	public AbstractSfPrevSoldCode(int codeType, String code, String codeName) {
		this.codeType = codeType;
		this.code = code;
		this.codeName = codeName;
	}

	public int getCodeId() {
		return this.codeId;
	}

	public void setCodeId(int codeId) {
		this.codeId = codeId;
	}

	public int getCodeType() {
		return this.codeType;
	}

	public void setCodeType(int codeType) {
		this.codeType = codeType;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

}