package org.iii.ideas.catering_service.dao;

//Generated 2015/2/3 上午 09:25:59 by Hibernate Tools 3.4.0.CR1

/**
* SfProduct generated by hbm2java
*/
public abstract class AbstractSfProduct implements java.io.Serializable {

	private Long id;
	private String name;
	private long supplierCompanyId;
	private long manufacturerId;
	private String preservedMethod;
	private String soldway;
	private String packages;
	private String certification;
	private String certificationId;
	private String appliedNoByJdf;
	private String barCode;

	public AbstractSfProduct() {
	}

	public AbstractSfProduct(String name, long supplierCompanyId, long manufacturerId,
			String preservedMethod, String soldway, String packages) {
		this.name = name;
		this.supplierCompanyId = supplierCompanyId;
		this.manufacturerId = manufacturerId;
		this.preservedMethod = preservedMethod;
		this.soldway = soldway;
		this.packages = packages;
	}

	public AbstractSfProduct(String name, long supplierCompanyId, long manufacturerId,
			String preservedMethod, String soldway, String packages,
			String certification, String certificationId,
			String appliedNoByJdf, String barCode) {
		this.name = name;
		this.supplierCompanyId = supplierCompanyId;
		this.manufacturerId = manufacturerId;
		this.preservedMethod = preservedMethod;
		this.soldway = soldway;
		this.packages = packages;
		this.certification = certification;
		this.certificationId = certificationId;
		this.appliedNoByJdf = appliedNoByJdf;
		this.barCode = barCode;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getSupplierCompanyId() {
		return this.supplierCompanyId;
	}

	public void setSupplierCompanyId(long supplierCompanyId) {
		this.supplierCompanyId = supplierCompanyId;
	}

	public long getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(long manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	public String getPreservedMethod() {
		return this.preservedMethod;
	}

	public void setPreservedMethod(String preservedMethod) {
		this.preservedMethod = preservedMethod;
	}

	public String getSoldway() {
		return this.soldway;
	}

	public void setSoldway(String soldway) {
		this.soldway = soldway;
	}

	public String getPackages() {
		return this.packages;
	}

	public void setPackages(String packages) {
		this.packages = packages;
	}

	public String getCertification() {
		return this.certification;
	}

	public void setCertification(String certification) {
		this.certification = certification;
	}

	public String getCertificationId() {
		return this.certificationId;
	}

	public void setCertificationId(String certificationId) {
		this.certificationId = certificationId;
	}

	public String getAppliedNoByJdf() {
		return this.appliedNoByJdf;
	}

	public void setAppliedNoByJdf(String appliedNoByJdf) {
		this.appliedNoByJdf = appliedNoByJdf;
	}

	public String getBarCode() {
		return this.barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}
}