package org.iii.ideas.catering_service.dao;

//Generated 2015/2/3 上午 09:25:59 by Hibernate Tools 3.4.0.CR1

/**
* SfCompany generated by hbm2java
*/
public abstract class AbstractSfCompany implements java.io.Serializable {

	private Long id;
	private String name;
	private String address;
	private String tel;
	private String owner;

	public AbstractSfCompany() {
	}

	public AbstractSfCompany(String name, String address, String tel, String owner) {
		this.name = name;
		this.address = address;
		this.tel = tel;
		this.owner = owner;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}
}