package org.iii.ideas.catering_service.dao;

//Generated 2015/2/3 上午 09:25:59 by Hibernate Tools 3.4.0.CR1

/**
* SfCountyproductcategory generated by hbm2java
*/
public abstract class AbstractSfCountyProductCategory implements java.io.Serializable {

	private Long id;
	private long countyId;
	private long productId;
	private long categoryId;

	public AbstractSfCountyProductCategory() {
	}

	public AbstractSfCountyProductCategory(long countyId, long productId,
			long categoryId) {
		this.countyId = countyId;
		this.productId = productId;
		this.categoryId = categoryId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getCountyId() {
		return this.countyId;
	}

	public void setCountyId(long countyId) {
		this.countyId = countyId;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}
}