package org.iii.ideas.catering_service.dao;

//Generated 2015/2/3 上午 09:25:59 by Hibernate Tools 3.4.0.CR1

/**
 * SfCategory generated by hbm2java
 */
public abstract class AbstractSfCategory implements java.io.Serializable {

	private long id;
	private String name;

	public AbstractSfCategory() {
	}

	public AbstractSfCategory(String name) {
		this.name = name;
	}
	public AbstractSfCategory(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}