package org.iii.ideas.catering_service.dao;

// default package
// Generated 2014/6/26 �U�� 02:28:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Uploadfile generated by hbm2java
 */
public class Newsattachfiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4468507527151863340L;
	private Integer id;
	private Integer newsId;
	private String name;
	private String fileDesc;
	private String filePath;
	private Integer fileSize;
	private Date createTime;
	private Date updateTime;
	
	public static final String ID = "id";	//String
	public static final String NEWS_ID = "newsId";	//String
	public static final String NAME = "name";	//String
	public static final String FILE_DESC = "fileDesc";	//String
	public static final String FILE_PATH = "filePath";	//String
	public static final String FILE_SIZE = "fileSize";	//String
	public static final String CREATE_TIME = "createTime"; // String
	public static final String UPDATE_TIME = "updateTime"; // String

	public Newsattachfiles() {
	}

//	public Newsattachfiles(Integer id, Integer newsId, String name,
//			String filePath,Integer fileSize,Date createTime,Date updateTime) {
//		this.id = id;
//		this.newsId = newsId;
//		this.name = name;
//		this.filePath = filePath;
//		this.fileSize = fileSize;
//		this.createTime = createTime;
//		this.updateTime = updateTime;
//	}

//	public Newsattachfiles(Long uuid, String encodeFileName, String sourceType,
//			String targetId, String filePath, String mimeType,String extType, Date createTime,
//			Date updateTime) {
//		this.uuid = uuid;
//		this.encodeFileName = encodeFileName;
//		this.sourceType = sourceType;
//		this.targetId = targetId;
//		this.filePath = filePath;
//		this.mimeType = mimeType;
//		this.extType = extType;
//		this.createTime = createTime;
//		this.updateTime = updateTime;
//	}
	


	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNewsId() {
		return newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public Integer getFileSize() {
		return fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getFileDesc() {
		return fileDesc;
	}

	public void setFileDesc(String fileDesc) {
		this.fileDesc = fileDesc;
	}
}
