package org.iii.ideas.catering_service.dao;
// default package
// Generated 2014/6/6 �U�� 02:21:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Resetpwdlog generated by hbm2java
 */
public class Resetpwdlog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 58942140420276227L;
	private Integer logId;
	private String username;
	private String email;
	private String ts;
	private String sourceIp;
	private Date createTime;
	private Date updateTime;
	private String description;
	private String status;

	public Resetpwdlog() {
	}

	public Resetpwdlog(String username, String email, String ts, Date createTime, Date updateTime, String status) {
		this.username = username;
		this.email = email;
		this.ts = ts;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
	}

	public Resetpwdlog(String username, String email, String ts, String sourceIp, Date createTime, Date updateTime, String description, String status) {
		this.username = username;
		this.email = email;
		this.ts = ts;
		this.sourceIp = sourceIp;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.description = description;
		this.status = status;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getSourceIp() {
		return sourceIp;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

}
