package org.iii.ideas.catering_service.dao;

// Generated 2015/11/2 下午 06:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RestaurantStockIngredient generated by hbm2java
 */
public class RestaurantStockIngredient implements java.io.Serializable {

	private Integer id;
	private int restaurantId;
	private int ingredientId;
	private Date stockDate;
	private Date useDate;
	private Date manufactureDate;
	private Date expirationDate;
	private String lotNumber;
	private String origin;
	private String ingredientQuantity;
	private String ingredientUnit;
	private Integer ingredientAttr;
	private Integer enable;
	private Date createDate;
	private String createUser;
	private Date modifyDate;
	private String modifyUser;

	public RestaurantStockIngredient() {
	}

	public RestaurantStockIngredient(int restaurantId, int ingredientId,
			Date stockDate, Date useDate, Date createDate, String createUser) {
		this.restaurantId = restaurantId;
		this.ingredientId = ingredientId;
		this.stockDate = stockDate;
		this.useDate = useDate;
		this.createDate = createDate;
		this.createUser = createUser;
	}

	public RestaurantStockIngredient(int restaurantId, int ingredientId,
			Date stockDate, Date useDate, Date manufactureDate,
			Date expirationDate, String lotNumber, String origin,
			String ingredientQuantity, String ingredientUnit,
			Integer ingredientAttr, Integer enable, Date createDate,
			String createUser, Date modifyDate, String modifyUser) {
		this.restaurantId = restaurantId;
		this.ingredientId = ingredientId;
		this.stockDate = stockDate;
		this.useDate = useDate;
		this.manufactureDate = manufactureDate;
		this.expirationDate = expirationDate;
		this.lotNumber = lotNumber;
		this.origin = origin;
		this.ingredientQuantity = ingredientQuantity;
		this.ingredientUnit = ingredientUnit;
		this.ingredientAttr = ingredientAttr;
		this.enable = enable;
		this.createDate = createDate;
		this.createUser = createUser;
		this.modifyDate = modifyDate;
		this.modifyUser = modifyUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}

	public int getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(int ingredientId) {
		this.ingredientId = ingredientId;
	}

	public Date getStockDate() {
		return this.stockDate;
	}

	public void setStockDate(Date stockDate) {
		this.stockDate = stockDate;
	}

	public Date getUseDate() {
		return this.useDate;
	}

	public void setUseDate(Date useDate) {
		this.useDate = useDate;
	}

	public Date getManufactureDate() {
		return this.manufactureDate;
	}

	public void setManufactureDate(Date manufactureDate) {
		this.manufactureDate = manufactureDate;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public String getLotNumber() {
		return this.lotNumber;
	}

	public void setLotNumber(String lotNumber) {
		this.lotNumber = lotNumber;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getIngredientQuantity() {
		return this.ingredientQuantity;
	}

	public void setIngredientQuantity(String ingredientQuantity) {
		this.ingredientQuantity = ingredientQuantity;
	}

	public String getIngredientUnit() {
		return this.ingredientUnit;
	}

	public void setIngredientUnit(String ingredientUnit) {
		this.ingredientUnit = ingredientUnit;
	}

	public Integer getIngredientAttr() {
		return this.ingredientAttr;
	}

	public void setIngredientAttr(Integer ingredientAttr) {
		this.ingredientAttr = ingredientAttr;
	}

	public Integer getEnable() {
		return this.enable;
	}

	public void setEnable(Integer enable) {
		this.enable = enable;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getModifyUser() {
		return this.modifyUser;
	}

	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

}
