package org.iii.ideas.catering_service.dao;

// Generated 2015/11/2 下午 06:06:40 by Hibernate Tools 3.4.0.CR1

/**
 * Restaurantdishtype generated by hbm2java
 */
public class Restaurantdishtype implements java.io.Serializable {

	private Integer rdishTypeId;
	private int restaurantId;
	private String rdishTypeName;
	private Integer sortOrder;

	public Restaurantdishtype() {
	}

	public Restaurantdishtype(int restaurantId, String rdishTypeName) {
		this.restaurantId = restaurantId;
		this.rdishTypeName = rdishTypeName;
	}

	public Restaurantdishtype(int restaurantId, String rdishTypeName,
			Integer sortOrder) {
		this.restaurantId = restaurantId;
		this.rdishTypeName = rdishTypeName;
		this.sortOrder = sortOrder;
	}

	public Integer getRdishTypeId() {
		return this.rdishTypeId;
	}

	public void setRdishTypeId(Integer rdishTypeId) {
		this.rdishTypeId = rdishTypeId;
	}

	public int getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}

	public String getRdishTypeName() {
		return this.rdishTypeName;
	}

	public void setRdishTypeName(String rdishTypeName) {
		this.rdishTypeName = rdishTypeName;
	}

	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
