package org.iii.ideas.catering_service.dao;

// Generated 2015/11/2 下午 06:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Restaurantdish generated by hbm2java
 */
public class Restaurantdish implements java.io.Serializable {

	private Integer rdishId;
	private int restaurantId;
	private String rdishName;
	private String rdishTypeId;
	private int sortOrder;
	private String ingredientList;
	private int calorie;
	private String dishPicId;
	private int enable;
	private Date createDate;
	private String createUser;
	private Date modifyDate;
	private String modifyUser;

	public Restaurantdish() {
	}

	public Restaurantdish(int restaurantId, String rdishName,
			String rdishTypeId, int sortOrder, int calorie, String dishPicId,
			int enable, Date createDate, String createUser) {
		this.restaurantId = restaurantId;
		this.rdishName = rdishName;
		this.rdishTypeId = rdishTypeId;
		this.sortOrder = sortOrder;
		this.calorie = calorie;
		this.dishPicId = dishPicId;
		this.enable = enable;
		this.createDate = createDate;
		this.createUser = createUser;
	}

	public Restaurantdish(int restaurantId, String rdishName,
			String rdishTypeId, int sortOrder, String ingredientList,
			int calorie, String dishPicId, int enable, Date createDate,
			String createUser, Date modifyDate, String modifyUser) {
		this.restaurantId = restaurantId;
		this.rdishName = rdishName;
		this.rdishTypeId = rdishTypeId;
		this.sortOrder = sortOrder;
		this.ingredientList = ingredientList;
		this.calorie = calorie;
		this.dishPicId = dishPicId;
		this.enable = enable;
		this.createDate = createDate;
		this.createUser = createUser;
		this.modifyDate = modifyDate;
		this.modifyUser = modifyUser;
	}

	public Integer getRdishId() {
		return this.rdishId;
	}

	public void setRdishId(Integer rdishId) {
		this.rdishId = rdishId;
	}

	public int getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}

	public String getRdishName() {
		return this.rdishName;
	}

	public void setRdishName(String rdishName) {
		this.rdishName = rdishName;
	}

	public String getRdishTypeId() {
		return this.rdishTypeId;
	}

	public void setRdishTypeId(String rdishTypeId) {
		this.rdishTypeId = rdishTypeId;
	}

	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	public String getIngredientList() {
		return this.ingredientList;
	}

	public void setIngredientList(String ingredientList) {
		this.ingredientList = ingredientList;
	}

	public int getCalorie() {
		return this.calorie;
	}

	public void setCalorie(int calorie) {
		this.calorie = calorie;
	}

	public String getDishPicId() {
		return this.dishPicId;
	}

	public void setDishPicId(String dishPicId) {
		this.dishPicId = dishPicId;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getModifyUser() {
		return this.modifyUser;
	}

	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

}
