package org.iii.ideas.catering_service.dao;

// Generated 2015/11/2 下午 06:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Restaurantmenudish generated by hbm2java
 */
public class Restaurantmenudish implements java.io.Serializable {

	private Integer rmenuDishId;
	private int rmenuId;
	private int rdishId;
	private String menuDate;
	private int enable;
	private Date createDate;
	private String createUser;
	private String modifyDate;
	private byte[] modifyUser;

	public Restaurantmenudish() {
	}

	public Restaurantmenudish(int rmenuId, int rdishId, String menuDate,
			int enable, Date createDate, String createUser) {
		this.rmenuId = rmenuId;
		this.rdishId = rdishId;
		this.menuDate = menuDate;
		this.enable = enable;
		this.createDate = createDate;
		this.createUser = createUser;
	}

	public Restaurantmenudish(int rmenuId, int rdishId, String menuDate,
			int enable, Date createDate, String createUser, String modifyDate,
			byte[] modifyUser) {
		this.rmenuId = rmenuId;
		this.rdishId = rdishId;
		this.menuDate = menuDate;
		this.enable = enable;
		this.createDate = createDate;
		this.createUser = createUser;
		this.modifyDate = modifyDate;
		this.modifyUser = modifyUser;
	}

	public Integer getRmenuDishId() {
		return this.rmenuDishId;
	}

	public void setRmenuDishId(Integer rmenuDishId) {
		this.rmenuDishId = rmenuDishId;
	}

	public int getRmenuId() {
		return this.rmenuId;
	}

	public void setRmenuId(int rmenuId) {
		this.rmenuId = rmenuId;
	}

	public int getRdishId() {
		return this.rdishId;
	}

	public void setRdishId(int rdishId) {
		this.rdishId = rdishId;
	}

	public String getMenuDate() {
		return this.menuDate;
	}

	public void setMenuDate(String menuDate) {
		this.menuDate = menuDate;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(String modifyDate) {
		this.modifyDate = modifyDate;
	}

	public byte[] getModifyUser() {
		return this.modifyUser;
	}

	public void setModifyUser(byte[] modifyUser) {
		this.modifyUser = modifyUser;
	}

}
