package org.iii.ideas.catering_service.dao;

// Generated 2015/11/2 下午 06:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Restaurantingredient generated by hbm2java
 */
public class Restaurantingredient implements java.io.Serializable {

	private Integer ringredientId;
	private int restaurantId;
	private String ringredientName;
	private String productName;
	private String sourceCertification;
	private String certificationNo;
	private String brand;
	private String brandNo;
	private String manufacturer;
	private String supplierCompanyId;
	private Date createDate;
	private String createUser;
	private Date modifyDate;
	private String modifyUser;

	public Restaurantingredient() {
	}

	public Restaurantingredient(int restaurantId, String ringredientName,
			String supplierCompanyId, Date createDate, String createUser) {
		this.restaurantId = restaurantId;
		this.ringredientName = ringredientName;
		this.supplierCompanyId = supplierCompanyId;
		this.createDate = createDate;
		this.createUser = createUser;
	}

	public Restaurantingredient(int restaurantId, String ringredientName,
			String productName, String sourceCertification,
			String certificationNo, String brand, String brandNo,
			String manufacturer, String supplierCompanyId, Date createDate,
			String createUser, Date modifyDate, String modifyUser) {
		this.restaurantId = restaurantId;
		this.ringredientName = ringredientName;
		this.productName = productName;
		this.sourceCertification = sourceCertification;
		this.certificationNo = certificationNo;
		this.brand = brand;
		this.brandNo = brandNo;
		this.manufacturer = manufacturer;
		this.supplierCompanyId = supplierCompanyId;
		this.createDate = createDate;
		this.createUser = createUser;
		this.modifyDate = modifyDate;
		this.modifyUser = modifyUser;
	}

	public Integer getRingredientId() {
		return this.ringredientId;
	}

	public void setRingredientId(Integer ringredientId) {
		this.ringredientId = ringredientId;
	}

	public int getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}

	public String getRingredientName() {
		return this.ringredientName;
	}

	public void setRingredientName(String ringredientName) {
		this.ringredientName = ringredientName;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getSourceCertification() {
		return this.sourceCertification;
	}

	public void setSourceCertification(String sourceCertification) {
		this.sourceCertification = sourceCertification;
	}

	public String getCertificationNo() {
		return this.certificationNo;
	}

	public void setCertificationNo(String certificationNo) {
		this.certificationNo = certificationNo;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getBrandNo() {
		return this.brandNo;
	}

	public void setBrandNo(String brandNo) {
		this.brandNo = brandNo;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getSupplierCompanyId() {
		return this.supplierCompanyId;
	}

	public void setSupplierCompanyId(String supplierCompanyId) {
		this.supplierCompanyId = supplierCompanyId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getModifyUser() {
		return this.modifyUser;
	}

	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

}
