package org.iii.ideas.catering_service.dao;

// Generated 2015/11/2 �U�� 06:06:40 by Hibernate Tools 3.4.0.CR1

/**
 * Schoolfoodstreet generated by hbm2java
 */
public class Schoolfoodstreet implements java.io.Serializable {

	private Integer sfstreetId;
	private int schoolId;
	private String sfstreetName;

	public Schoolfoodstreet() {
	}

	public Schoolfoodstreet(Integer sfstreetId , int schoolId, String sfstreetName) {
		this.sfstreetId = sfstreetId;
		this.schoolId = schoolId;
		this.sfstreetName = sfstreetName;
	}
	
	public Schoolfoodstreet(int schoolId, String sfstreetName) {
		this.schoolId = schoolId;
		this.sfstreetName = sfstreetName;
	}

	public Integer getSfstreetId() {
		return this.sfstreetId;
	}

	public void setSfstreetId(Integer sfstreetId) {
		this.sfstreetId = sfstreetId;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	public String getSfstreetName() {
		return this.sfstreetName;
	}

	public void setSfstreetName(String sfstreetName) {
		this.sfstreetName = sfstreetName;
	}

}
