package org.iii.ideas.catering_service.dao;

// default package
// Generated 2014/6/26 �U�� 02:28:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Uploadfile generated by hbm2java
 */
public class Uploadfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4468507527151863340L;
	private Long uuid;
	private String encodeFileName;
	private String sourceType;
	private String targetId;
	private String filePath;
	private String mimeType;
	private String extType;
	private Date createTime;
	private Date updateTime;
	private String OriginalFileName;

	public Uploadfile() {
	}

	public Uploadfile(Long uuid, String encodeFileName, String filePath,
			String mimeType,String extType) {
		this.uuid = uuid;
		this.encodeFileName = encodeFileName;
		this.filePath = filePath;
		this.mimeType = mimeType;
		this.extType = extType;
	}

	public Uploadfile(Long uuid, String encodeFileName, String sourceType,
			String targetId, String filePath, String mimeType,String extType, Date createTime,
			Date updateTime) {
		this.uuid = uuid;
		this.encodeFileName = encodeFileName;
		this.sourceType = sourceType;
		this.targetId = targetId;
		this.filePath = filePath;
		this.mimeType = mimeType;
		this.extType = extType;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}


	public String getEncodeFileName() {
		return this.encodeFileName;
	}

	public void setEncodeFileName(String encodeFileName) {
		this.encodeFileName = encodeFileName;
	}

	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	public String getTargetId() {
		return this.targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Long getUuid() {
		return uuid;
	}

	public void setUuid(Long uuid) {
		this.uuid = uuid;
	}

	public String getExtType() {
		return extType;
	}

	public void setExtType(String extType) {
		this.extType = extType;
	}

	public String getOriginalFileName() {
		return OriginalFileName;
	}

	public void setOriginalFileName(String originalFileName) {
		OriginalFileName = originalFileName;
	}

}
