package org.iii.ideas.catering_service.dao;

// Generated 2015/11/2 下午 06:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Userrelation generated by hbm2java
 */
public class Userrelation implements java.io.Serializable {

	private Integer id;
	private String parent;
	private String parentType;
	private String child;
	private String authorizeType;
	private String authorizeUserType;
	private String authorizeTarget;
	private String authorizeTargetType;
	private String canCreateAccount;
	private String canDeleteAccount;
	private String canEditAccount;
	private String canCreateRestaurant;
	private String canDeleteRestaurant;
	private String canEditRestaurant;
	private String canUploadMenu;
	private String status;
	private String createUser;
	private Date createDate;
	private String modifyUser;
	private Date modifyDate;

	public Userrelation() {
	}

	public Userrelation(String parent, String parentType, String child,
			String authorizeType, String authorizeUserType,
			String canCreateAccount, String canDeleteAccount,
			String canEditAccount, String canCreateRestaurant,
			String canDeleteRestaurant, String canEditRestaurant,
			String canUploadMenu, String status, String createUser,
			Date createDate) {
		this.parent = parent;
		this.parentType = parentType;
		this.child = child;
		this.authorizeType = authorizeType;
		this.authorizeUserType = authorizeUserType;
		this.canCreateAccount = canCreateAccount;
		this.canDeleteAccount = canDeleteAccount;
		this.canEditAccount = canEditAccount;
		this.canCreateRestaurant = canCreateRestaurant;
		this.canDeleteRestaurant = canDeleteRestaurant;
		this.canEditRestaurant = canEditRestaurant;
		this.canUploadMenu = canUploadMenu;
		this.status = status;
		this.createUser = createUser;
		this.createDate = createDate;
	}

	public Userrelation(String parent, String parentType, String child,
			String authorizeType, String authorizeUserType,
			String authorizeTarget, String authorizeTargetType,
			String canCreateAccount, String canDeleteAccount,
			String canEditAccount, String canCreateRestaurant,
			String canDeleteRestaurant, String canEditRestaurant,
			String canUploadMenu, String status, String createUser,
			Date createDate, String modifyUser, Date modifyDate) {
		this.parent = parent;
		this.parentType = parentType;
		this.child = child;
		this.authorizeType = authorizeType;
		this.authorizeUserType = authorizeUserType;
		this.authorizeTarget = authorizeTarget;
		this.authorizeTargetType = authorizeTargetType;
		this.canCreateAccount = canCreateAccount;
		this.canDeleteAccount = canDeleteAccount;
		this.canEditAccount = canEditAccount;
		this.canCreateRestaurant = canCreateRestaurant;
		this.canDeleteRestaurant = canDeleteRestaurant;
		this.canEditRestaurant = canEditRestaurant;
		this.canUploadMenu = canUploadMenu;
		this.status = status;
		this.createUser = createUser;
		this.createDate = createDate;
		this.modifyUser = modifyUser;
		this.modifyDate = modifyDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

	public String getChild() {
		return this.child;
	}

	public void setChild(String child) {
		this.child = child;
	}

	public String getAuthorizeType() {
		return this.authorizeType;
	}

	public void setAuthorizeType(String authorizeType) {
		this.authorizeType = authorizeType;
	}

	public String getAuthorizeUserType() {
		return this.authorizeUserType;
	}

	public void setAuthorizeUserType(String authorizeUserType) {
		this.authorizeUserType = authorizeUserType;
	}

	public String getAuthorizeTarget() {
		return this.authorizeTarget;
	}

	public void setAuthorizeTarget(String authorizeTarget) {
		this.authorizeTarget = authorizeTarget;
	}

	public String getAuthorizeTargetType() {
		return this.authorizeTargetType;
	}

	public void setAuthorizeTargetType(String authorizeTargetType) {
		this.authorizeTargetType = authorizeTargetType;
	}

	public String getCanCreateAccount() {
		return this.canCreateAccount;
	}

	public void setCanCreateAccount(String canCreateAccount) {
		this.canCreateAccount = canCreateAccount;
	}

	public String getCanDeleteAccount() {
		return this.canDeleteAccount;
	}

	public void setCanDeleteAccount(String canDeleteAccount) {
		this.canDeleteAccount = canDeleteAccount;
	}

	public String getCanEditAccount() {
		return this.canEditAccount;
	}

	public void setCanEditAccount(String canEditAccount) {
		this.canEditAccount = canEditAccount;
	}

	public String getCanCreateRestaurant() {
		return this.canCreateRestaurant;
	}

	public void setCanCreateRestaurant(String canCreateRestaurant) {
		this.canCreateRestaurant = canCreateRestaurant;
	}

	public String getCanDeleteRestaurant() {
		return this.canDeleteRestaurant;
	}

	public void setCanDeleteRestaurant(String canDeleteRestaurant) {
		this.canDeleteRestaurant = canDeleteRestaurant;
	}

	public String getCanEditRestaurant() {
		return this.canEditRestaurant;
	}

	public void setCanEditRestaurant(String canEditRestaurant) {
		this.canEditRestaurant = canEditRestaurant;
	}

	public String getCanUploadMenu() {
		return this.canUploadMenu;
	}

	public void setCanUploadMenu(String canUploadMenu) {
		this.canUploadMenu = canUploadMenu;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModifyUser() {
		return this.modifyUser;
	}

	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
