//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.13 at 10:25:24 AM CST 
//


package org.iii.ideas.catering_service.ws.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iii.ideas.catering_service.ws.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UploadProductRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadProductRequest");
    private final static QName _UploadBatchProductResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadBatchProductResponse");
    private final static QName _UploadBatchProductRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadBatchProductRequest");
    private final static QName _DeleteBatchProductRequest_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "DeleteBatchProductRequest");
    private final static QName _DeleteBatchProductResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "DeleteBatchProductResponse");
    private final static QName _UploadProductResponse_QNAME = new QName("http://twfoodtrace.org.tw/FcloudDataschemas", "UploadProductResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iii.ideas.catering_service.ws.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UploadBatchProductRequestType }
     * 
     */
    public UploadBatchProductRequestType createUploadBatchProductRequestType() {
        return new UploadBatchProductRequestType();
    }

    /**
     * Create an instance of {@link UploadBatchProductRequestType.Sources }
     * 
     */
    public UploadBatchProductRequestType.Sources createUploadBatchProductRequestTypeSources() {
        return new UploadBatchProductRequestType.Sources();
    }

    /**
     * Create an instance of {@link UploadBatchProductRequestType.Sources.SourceItem }
     * 
     */
    public UploadBatchProductRequestType.Sources.SourceItem createUploadBatchProductRequestTypeSourcesSourceItem() {
        return new UploadBatchProductRequestType.Sources.SourceItem();
    }

    /**
     * Create an instance of {@link FoodResponseType }
     * 
     */
    public FoodResponseType createFoodResponseType() {
        return new FoodResponseType();
    }

    /**
     * Create an instance of {@link UploadProductRequestType }
     * 
     */
    public UploadProductRequestType createUploadProductRequestType() {
        return new UploadProductRequestType();
    }

    /**
     * Create an instance of {@link DeleteBatchProductRequestType }
     * 
     */
    public DeleteBatchProductRequestType createDeleteBatchProductRequestType() {
        return new DeleteBatchProductRequestType();
    }

    /**
     * Create an instance of {@link UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList }
     * 
     */
    public UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList createUploadBatchProductRequestTypeSourcesSourceItemSourceInspectionFileList() {
        return new UploadBatchProductRequestType.Sources.SourceItem.SourceInspectionFileList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadProductRequest")
    public JAXBElement<UploadProductRequestType> createUploadProductRequest(UploadProductRequestType value) {
        return new JAXBElement<UploadProductRequestType>(_UploadProductRequest_QNAME, UploadProductRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadBatchProductResponse")
    public JAXBElement<FoodResponseType> createUploadBatchProductResponse(FoodResponseType value) {
        return new JAXBElement<FoodResponseType>(_UploadBatchProductResponse_QNAME, FoodResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UploadBatchProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadBatchProductRequest")
    public JAXBElement<UploadBatchProductRequestType> createUploadBatchProductRequest(UploadBatchProductRequestType value) {
        return new JAXBElement<UploadBatchProductRequestType>(_UploadBatchProductRequest_QNAME, UploadBatchProductRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteBatchProductRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "DeleteBatchProductRequest")
    public JAXBElement<DeleteBatchProductRequestType> createDeleteBatchProductRequest(DeleteBatchProductRequestType value) {
        return new JAXBElement<DeleteBatchProductRequestType>(_DeleteBatchProductRequest_QNAME, DeleteBatchProductRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "DeleteBatchProductResponse")
    public JAXBElement<FoodResponseType> createDeleteBatchProductResponse(FoodResponseType value) {
        return new JAXBElement<FoodResponseType>(_DeleteBatchProductResponse_QNAME, FoodResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", name = "UploadProductResponse")
    public JAXBElement<FoodResponseType> createUploadProductResponse(FoodResponseType value) {
        return new JAXBElement<FoodResponseType>(_UploadProductResponse_QNAME, FoodResponseType.class, null, value);
    }

}
