//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.13 at 10:25:24 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://twfoodtrace.org.tw/FcloudDataschemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.iii.ideas.catering_service.ws.schema;
