//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.13 at 10:25:24 AM CST 
//


package org.iii.ideas.catering_service.ws.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UploadProductRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UploadProductRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SchoolId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Staple1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Staple2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MainCourse1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MainCourse2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MainCourse3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SideDish1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SideDish2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SideDish3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SideDish4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SideDish5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SideDish6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Vegetable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Soup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Extra1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Extra2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Grains" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MeatBeans" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vegetables" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Oils" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fruits" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Milk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Calories" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UploadProductRequestType", propOrder = {
    "action",
    "messageId",
    "companyAccount",
    "companyId",
    "companyName",
    "serviceDate",
    "schoolId",
    "staple1",
    "staple2",
    "mainCourse1",
    "mainCourse2",
    "mainCourse3",
    "sideDish1",
    "sideDish2",
    "sideDish3",
    "sideDish4",
    "sideDish5",
    "sideDish6",
    "vegetable",
    "soup",
    "extra1",
    "extra2",
    "grains",
    "meatBeans",
    "vegetables",
    "oils",
    "fruits",
    "milk",
    "calories"
})

@XmlRootElement(name="UploadProductRequestType")
public class UploadProductRequestType {

    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "MessageId", required = true)
    protected String messageId;
    @XmlElement(name = "CompanyAccount", required = true)
    protected String companyAccount;
    @XmlElement(name = "CompanyId", required = true)
    protected String companyId;
    @XmlElement(name = "CompanyName", required = true)
    protected String companyName;
    @XmlElement(name = "ServiceDate", required = true)
    protected String serviceDate;
    @XmlElement(name = "SchoolId", required = true)
    protected String schoolId;
    @XmlElement(name = "Staple1", required = true)
    protected String staple1;
    @XmlElement(name = "Staple2")
    protected String staple2;
    @XmlElement(name = "MainCourse1", required = true)
    protected String mainCourse1;
    @XmlElement(name = "MainCourse2")
    protected String mainCourse2;
    @XmlElement(name = "MainCourse3")
    protected String mainCourse3;
    @XmlElement(name = "SideDish1")
    protected String sideDish1;
    @XmlElement(name = "SideDish2")
    protected String sideDish2;
    @XmlElement(name = "SideDish3")
    protected String sideDish3;
    @XmlElement(name = "SideDish4")
    protected String sideDish4;
    @XmlElement(name = "SideDish5")
    protected String sideDish5;
    @XmlElement(name = "SideDish6")
    protected String sideDish6;
    @XmlElement(name = "Vegetable")
    protected String vegetable;
    @XmlElement(name = "Soup")
    protected String soup;
    @XmlElement(name = "Extra1")
    protected String extra1;
    @XmlElement(name = "Extra2")
    protected String extra2;
    @XmlElement(name = "Grains", required = true)
    protected String grains;
    @XmlElement(name = "MeatBeans", required = true)
    protected String meatBeans;
    @XmlElement(name = "Vegetables", required = true)
    protected String vegetables;
    @XmlElement(name = "Oils", required = true)
    protected String oils;
    @XmlElement(name = "Fruits", required = true)
    protected String fruits;
    @XmlElement(name = "Milk", required = true)
    protected String milk;
    @XmlElement(name = "Calories", required = true)
    protected String calories;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the companyAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyAccount() {
        return companyAccount;
    }

    /**
     * Sets the value of the companyAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyAccount(String value) {
        this.companyAccount = value;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyId(String value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the serviceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDate() {
        return serviceDate;
    }

    /**
     * Sets the value of the serviceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDate(String value) {
        this.serviceDate = value;
    }

    /**
     * Gets the value of the schoolId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * Sets the value of the schoolId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolId(String value) {
        this.schoolId = value;
    }

    /**
     * Gets the value of the staple1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaple1() {
        return staple1;
    }

    /**
     * Sets the value of the staple1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaple1(String value) {
        this.staple1 = value;
    }

    /**
     * Gets the value of the staple2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaple2() {
        return staple2;
    }

    /**
     * Sets the value of the staple2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaple2(String value) {
        this.staple2 = value;
    }

    /**
     * Gets the value of the mainCourse1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainCourse1() {
        return mainCourse1;
    }

    /**
     * Sets the value of the mainCourse1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainCourse1(String value) {
        this.mainCourse1 = value;
    }

    /**
     * Gets the value of the mainCourse2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainCourse2() {
        return mainCourse2;
    }

    /**
     * Sets the value of the mainCourse2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainCourse2(String value) {
        this.mainCourse2 = value;
    }

    /**
     * Gets the value of the mainCourse3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainCourse3() {
        return mainCourse3;
    }

    /**
     * Sets the value of the mainCourse3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainCourse3(String value) {
        this.mainCourse3 = value;
    }

    /**
     * Gets the value of the sideDish1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSideDish1() {
        return sideDish1;
    }

    /**
     * Sets the value of the sideDish1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSideDish1(String value) {
        this.sideDish1 = value;
    }

    /**
     * Gets the value of the sideDish2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSideDish2() {
        return sideDish2;
    }

    /**
     * Sets the value of the sideDish2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSideDish2(String value) {
        this.sideDish2 = value;
    }

    /**
     * Gets the value of the sideDish3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSideDish3() {
        return sideDish3;
    }

    /**
     * Sets the value of the sideDish3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSideDish3(String value) {
        this.sideDish3 = value;
    }

    /**
     * Gets the value of the sideDish4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSideDish4() {
        return sideDish4;
    }

    /**
     * Sets the value of the sideDish4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSideDish4(String value) {
        this.sideDish4 = value;
    }

    /**
     * Gets the value of the sideDish5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSideDish5() {
        return sideDish5;
    }

    /**
     * Sets the value of the sideDish5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSideDish5(String value) {
        this.sideDish5 = value;
    }

    /**
     * Gets the value of the sideDish6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSideDish6() {
        return sideDish6;
    }

    /**
     * Sets the value of the sideDish6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSideDish6(String value) {
        this.sideDish6 = value;
    }

    /**
     * Gets the value of the vegetable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVegetable() {
        return vegetable;
    }

    /**
     * Sets the value of the vegetable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVegetable(String value) {
        this.vegetable = value;
    }

    /**
     * Gets the value of the soup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoup() {
        return soup;
    }

    /**
     * Sets the value of the soup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoup(String value) {
        this.soup = value;
    }

    /**
     * Gets the value of the extra1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * Sets the value of the extra1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtra1(String value) {
        this.extra1 = value;
    }

    /**
     * Gets the value of the extra2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * Sets the value of the extra2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtra2(String value) {
        this.extra2 = value;
    }

    /**
     * Gets the value of the grains property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrains() {
        return grains;
    }

    /**
     * Sets the value of the grains property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrains(String value) {
        this.grains = value;
    }

    /**
     * Gets the value of the meatBeans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeatBeans() {
        return meatBeans;
    }

    /**
     * Sets the value of the meatBeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeatBeans(String value) {
        this.meatBeans = value;
    }

    /**
     * Gets the value of the vegetables property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVegetables() {
        return vegetables;
    }

    /**
     * Sets the value of the vegetables property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVegetables(String value) {
        this.vegetables = value;
    }

    /**
     * Gets the value of the oils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOils() {
        return oils;
    }

    /**
     * Sets the value of the oils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOils(String value) {
        this.oils = value;
    }

    /**
     * Gets the value of the fruits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFruits() {
        return fruits;
    }

    /**
     * Sets the value of the fruits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFruits(String value) {
        this.fruits = value;
    }

    /**
     * Gets the value of the milk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMilk() {
        return milk;
    }

    /**
     * Sets the value of the milk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMilk(String value) {
        this.milk = value;
    }

    /**
     * Gets the value of the calories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalories() {
        return calories;
    }

    /**
     * Sets the value of the calories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalories(String value) {
        this.calories = value;
    }

}
